### ISSUE TITLE
Controller 'tabset', required by directive 'tabContentTransclude', can't be found!

### ISSUE THREAD

**Issue by sasikumardr** [quantumui/quantumui#41]
I was trying to use tabcontroller in my app. But I am getting following error in console and neither tabs not tab contents are displayed.

can someone please check if this is real issue? pelase let me know if any more info is needed.

I am using angularjs 1.4.1 and QuantumUI 0.0.1

Error: [$compile:ctreq] Controller 'tabset', required by directive 'tabContentTransclude', can't be found!
http://errors.angularjs.org/1.4.1/$compile/ctreq?p0=tabset&p1=tabContentTransclude
    at REGEX_STRING_REGEXP (http://localhost:3000/lib/angular/angular.js:68:12)
    at getControllers (http://localhost:3000/lib/angular/angular.js:7999:19)
    at nodeLinkFn (http://localhost:3000/lib/angular/angular.js:8146:33)
    at compositeLinkFn (http://localhost:3000/lib/angular/angular.js:7534:13)
    at publicLinkFn (http://localhost:3000/lib/angular/angular.js:7409:30)
    at $get.boundTranscludeFn (http://localhost:3000/lib/angular/angular.js:7553:16)
    at controllersBoundTransclude (http://localhost:3000/lib/angular/angular.js:8169:18)
    at ngDirective.link (http://localhost:3000/lib/angular/angular.js:27808:5)
    at invokeLinkFn (http://localhost:3000/lib/angular/angular.js:8642:9)
    at nodeLinkFn (http://localhost:3000/lib/angular/angular.js:8142:11) <div class="tab-content" ng-transclude="">

```
 <div data-nq-tabset="" data-responsive="true" >
        <div data-nq-tab="" data-heading="Basic Info">
            <form novalidate class="form-horizontal">
               ...form contents....
            </form>
         </div>

       <div data-nq-tab="" data-heading="Advanced">
            <form>
                <fieldset>
                    <legend>Advanced</legend>
                     ............Form contents.............
                </fieldset>
            </form>
        </div>
  </div>
```

**Comment by mehmetotkun** [comment]
if you use angular-ui tab there would be conflict.
